
server:
  port: 8082
  servlet:
    context-path: /pagamento

spring:
  application:
    name: pagamento
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibermate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enable: false
  datasource:
    url: jdbc:mysql://localhost:3306/pagamento?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

crud:
  rabbitmq:
    exchange: crud.exchange
    routingkey: crud.produto.routingkey
    queue: crud.produto.queue

security:
  jwt: 
    token: 
      secret-key: chave_microservices
